export const mockLinks = [
  {
    id: "1",
    type: "bio",
    title: "Portfolio Website",
    url: "https://johndoe.dev",
    shortUrl: "linkcraft.co/portfolio",
    description: "Check out my latest work and projects",
    active: true,
    clicks: 1247,
    icon: "🌐",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    type: "bio",
    title: "Latest Blog Post",
    url: "https://johndoe.dev/blog/latest",
    shortUrl: "linkcraft.co/blog",
    description: "My thoughts on modern web development",
    active: true,
    clicks: 892,
    icon: "📝",
    createdAt: "2024-01-14T15:30:00Z",
  },
  {
    id: "3",
    type: "short",
    title: "Product Launch",
    url: "https://myproduct.com/launch",
    shortUrl: "linkcraft.co/launch",
    description: "Our exciting new product launch",
    active: true,
    clicks: 2156,
    createdAt: "2024-01-13T09:15:00Z",
  },
  {
    id: "4",
    type: "short",
    title: "Newsletter Signup",
    url: "https://newsletter.example.com/signup",
    shortUrl: "linkcraft.co/newsletter",
    description: "Join our weekly newsletter",
    active: true,
    clicks: 1834,
    createdAt: "2024-01-12T14:20:00Z",
  },
]

export const mockAnalytics = {
  totalClicks: 12847,
  totalLinks: 24,
  totalQRScans: 1893,
  totalBioViews: 5621,
  clicksOverTime: [
    { date: "2024-01-01", clicks: 120 },
    { date: "2024-01-02", clicks: 145 },
    { date: "2024-01-03", clicks: 167 },
    { date: "2024-01-04", clicks: 189 },
    { date: "2024-01-05", clicks: 203 },
    { date: "2024-01-06", clicks: 178 },
    { date: "2024-01-07", clicks: 234 },
  ],
  topCountries: [
    { code: "US", name: "United States", clicks: 4521, flag: "🇺🇸" },
    { code: "GB", name: "United Kingdom", clicks: 2134, flag: "🇬🇧" },
    { code: "CA", name: "Canada", clicks: 1876, flag: "🇨🇦" },
    { code: "DE", name: "Germany", clicks: 1234, flag: "🇩🇪" },
    { code: "FR", name: "France", clicks: 987, flag: "🇫🇷" },
  ],
  deviceBreakdown: [
    { device: "Desktop", clicks: 6423, percentage: 50 },
    { device: "Mobile", clicks: 5139, percentage: 40 },
    { device: "Tablet", clicks: 1285, percentage: 10 },
  ],
  referrerSources: [
    { source: "Direct", clicks: 5139, percentage: 40 },
    { source: "Social Media", clicks: 3854, percentage: 30 },
    { source: "Search Engines", clicks: 2569, percentage: 20 },
    { source: "Email", clicks: 1285, percentage: 10 },
  ],
  recentActivity: [
    {
      id: "1",
      action: "Link clicked",
      link: "Portfolio Website",
      country: "🇺🇸 US",
      time: "2 minutes ago",
    },
    {
      id: "2",
      action: "QR code scanned",
      link: "Contact Info",
      country: "🇬🇧 UK",
      time: "5 minutes ago",
    },
    {
      id: "3",
      action: "Bio page viewed",
      link: "johndoe.dev",
      country: "🇨🇦 CA",
      time: "8 minutes ago",
    },
    {
      id: "4",
      action: "Link clicked",
      link: "Latest Blog Post",
      country: "🇩🇪 DE",
      time: "12 minutes ago",
    },
  ],
}
